security:
    enable_authenticator_manager: true

    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_MODERATOR]
        ROLE_MODERATOR:    ROLE_USER


    password_hashers:
        App\Entity\User:
            algorithm: 'sodium'

    providers:
        app_user_provider:
           entity:
             class: App\Entity\User
             property: email #login methode

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|build|images|js)/
            security: false

        main:
            pattern: ^/
            lazy: true
            provider: app_user_provider
            user_checker: App\EventListener\PreAuthListener
            entry_point: App\Security\LoginFormAuthenticator
            custom_authenticator: App\Security\LoginFormAuthenticator

            login_throttling:
                max_attempts: 2

            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                always_remember_me: true
                remember_me_parameter: _remember_me
                path: /

            logout:
                path: security_logout
                target: index

    access_control:
        - { path: '^/login', roles: PUBLIC_ACCESS }
        - { path: '^/your', roles: [IS_AUTHENTICATED_FULLY, IS_AUTHENTICATED_REMEMBERED] }