twig:
    paths: 
      '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator
      '%kernel.project_dir%/templates/superuser/rankone/': admin_root
      '%kernel.project_dir%/templates/superuser/ranktwo/': mod_root
      '%kernel.project_dir%/templates/superuser/ranktwo/ressources/': ressources_dir
      '%kernel.project_dir%/templates/superuser': backend_root
      '%kernel.project_dir%/templates/user': user
      '%kernel.project_dir%/templates/components': components

    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
      app_name: '%env(APP_NAME)%'
    form_themes:
        - bootstrap_3_layout.html.twig
        - _formTheme.html.twig